# Generated by Django 2.2.5 on 2019-11-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now=True)),
                ('directions_and_introductory_text', models.TextField(max_length=5000)),
                ('primary_source_text', models.TextField(max_length=20000)),
                ('question_1', models.TextField(max_length=2000)),
                ('notes_for_question_1', models.TextField(blank=True, max_length=2000)),
                ('question_2', models.TextField(blank=True, max_length=2000)),
                ('notes_for_question_2', models.TextField(blank=True, max_length=2000)),
                ('question_3', models.TextField(blank=True, max_length=2000)),
                ('notes_for_question_3', models.TextField(blank=True, max_length=2000)),
                ('question_4', models.TextField(blank=True, max_length=2000)),
                ('notes_for_question_4', models.TextField(blank=True, max_length=2000)),
                ('question_5', models.TextField(blank=True, max_length=2000)),
                ('notes_for_question_5', models.TextField(blank=True, max_length=2000)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
