# Generated by Django 2.2.5 on 2019-11-05 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191104_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_for_question_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_for_question_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_for_question_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_for_question_4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='notes_for_question_5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_5',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
