# Generated by Django 2.2.6 on 2019-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizresponse_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='respondent',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='id_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
