# Generated by Django 2.2.6 on 2019-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20191126_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='response_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
