# Generated by Django 2.2.5 on 2019-11-05 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respondent', '0002_respondent_id_number'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='respondent.Respondent'),
            preserve_default=False,
        ),
    ]
