# Generated by Django 2.2.5 on 2019-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
